# Generated by Django 5.2.7 on 2026-01-20 09:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(error_messages={'blank': 'このフィールドは必須です。', 'unique': 'そのユーザ名は既に存在します。'}, help_text='ユーザ名は必須です。150文字以内。英字、数字、@/./+/-/_ のみ使用可能です。', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='有効なユーザ名を入力してください。この値には英字、数字、@/./+/-/_ 文字のみを含めることができます。', regex='^[\\w.@+-]+$')], verbose_name='ユーザ名')),
                ('nickname', models.CharField(default='User:96977ef1c5aa', max_length=30, verbose_name='ニックネーム')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザ',
                'verbose_name_plural': 'ユーザ一覧',
            },
        ),
    ]
