# Generated by Django 5.2.7 on 2025-11-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'ユーザ', 'verbose_name_plural': 'ユーザ一覧'},
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名0098b8ab3f72', max_length=30, unique=True, verbose_name='ニックネーム'),
        ),
    ]
