# Generated by Django 5.2.7 on 2025-12-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_options_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='匿名f6ef8265b7d1', max_length=30, unique=True, verbose_name='ニックネーム'),
        ),
    ]
