# Generated by Django 5.2.7 on 2025-12-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='User:ba16804594bc', max_length=30, unique=True, verbose_name='ニックネーム'),
        ),
    ]
