# Generated by Django 5.2.7 on 2025-12-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='User:414909c5a527', max_length=30, verbose_name='ニックネーム'),
        ),
    ]
