# Generated by Django 5.2.7 on 2025-12-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='User:cab23af9fc4d', max_length=30, verbose_name='ニックネーム'),
        ),
    ]
