# Generated by Django 5.2.7 on 2025-12-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='User:5876dba5651d', max_length=30, verbose_name='ニックネーム'),
        ),
    ]
