# Generated by Django 5.2.7 on 2025-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='User:80c7af6391ae', max_length=30, verbose_name='ニックネーム'),
        ),
    ]
