# Generated by Django 5.2.7 on 2025-12-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='User:214b3b21745a', max_length=30, verbose_name='ニックネーム'),
        ),
    ]
