# Generated by Django 5.2.7 on 2026-01-20 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartrates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '心拍数',
                'verbose_name_plural': '心拍数一覧',
            },
        ),
        migrations.CreateModel(
            name='WearOSIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wearos_integration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WearOS連携',
                'verbose_name_plural': 'WearOS連携一覧',
            },
        ),
    ]
