# Generated by Django 5.2.7 on 2025-12-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartrates', '0002_wearosintegration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartrate',
            options={'verbose_name': '心拍数', 'verbose_name_plural': '心拍数一覧'},
        ),
        migrations.AlterModelOptions(
            name='wearosintegration',
            options={'verbose_name': 'WearOS連携', 'verbose_name_plural': 'WearOS連携一覧'},
        ),
        migrations.AddField(
            model_name='wearosintegration',
            name='is_connected',
            field=models.BooleanField(default=True),
        ),
    ]
