# Generated by Django 5.2.7 on 2025-12-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartrates', '0003_alter_heartrate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearosintegration',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
