# Generated by Django 5.2.7 on 2026-01-20 09:00

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='スタンプ名は必須です。固有の名前を指定してください。', max_length=100, unique=True, verbose_name='スタンプ名')),
                ('color', models.CharField(choices=[('textcolor-red', '赤'), ('textcolor-orange', '橙'), ('textcolor-yellow', '黄'), ('textcolor-lime', '黄緑'), ('textcolor-green', '緑'), ('textcolor-cyan', '水色'), ('textcolor-blue', '青'), ('textcolor-purple', '紫')], default='textcolor-blue', help_text='気持ちの色を選択してください。', max_length=16, verbose_name='スタンプ色')),
                ('score', models.IntegerField(default=0, help_text='スタンプのスコアを整数で指定してください。', verbose_name='スコア')),
                ('image', models.ImageField(blank=True, help_text='スタンプの画像ファイルをアップロードしてください。', null=True, upload_to='stamps/', verbose_name='スタンプ画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'スタンプ',
                'verbose_name_plural': 'スタンプ一覧',
            },
        ),
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, help_text='気持ちに関するコメントを入力してください。', max_length=500, verbose_name='コメント')),
                ('felt_at', models.DateTimeField(default=datetime.datetime(2026, 1, 20, 18, 0, 56, 432632), help_text='気持ちを感じた日時を指定してください。', verbose_name='感じた日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feelings', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feelings', to='feelings.stamp', verbose_name='スタンプ')),
            ],
            options={
                'verbose_name': '気持ち',
                'verbose_name_plural': '気持ち一覧',
            },
        ),
    ]
