# Generated by Django 5.2.7 on 2025-12-13 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeling',
            name='felt_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 13, 18, 8, 9, 490385), help_text='気持ちを感じた日時を指定してください。', verbose_name='感じた日時'),
        ),
        migrations.AddField(
            model_name='stamp',
            name='image',
            field=models.ImageField(blank=True, help_text='スタンプの画像ファイルをアップロードしてください。', null=True, upload_to='stamps/', verbose_name='スタンプ画像'),
        ),
    ]
