# Generated by Django 5.2.7 on 2025-12-14 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0002_feeling_felt_at_stamp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='felt_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 17, 41, 7, 852976), help_text='気持ちを感じた日時を指定してください。', verbose_name='感じた日時'),
        ),
    ]
