# Generated by Django 5.2.7 on 2025-12-14 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0004_alter_feeling_felt_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='color',
            field=models.CharField(choices=[('textcolor-red', '赤'), ('textcolor-orange', '橙'), ('textcolor-yellow', '黄'), ('textcolor-lime', '黄緑'), ('textcolor-green', '緑'), ('textcolor-cyan', '水色'), ('textcolor-blue', '青'), ('textcolor-purple', '紫')], default='textcolor-blue', help_text='感情の色を選択してください。', max_length=16, verbose_name='スタンプ色'),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='felt_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 19, 24, 43, 814571), help_text='気持ちを感じた日時を指定してください。', verbose_name='感じた日時'),
        ),
    ]
