# Generated by Django 5.2.7 on 2025-12-18 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0005_stamp_color_alter_feeling_felt_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='felt_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 18, 23, 53, 18, 936505), help_text='気持ちを感じた日時を指定してください。', verbose_name='感じた日時'),
        ),
    ]
