# Generated by Django 5.2.7 on 2025-12-18 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feelings', '0006_alter_feeling_felt_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='felt_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 19, 0, 17, 43, 18095), help_text='気持ちを感じた日時を指定してください。', verbose_name='感じた日時'),
        ),
    ]
